language: ruby
rvm:
  - 2.1.2
before_script:
  - "export DISPLAY=:99.0"
  - 'sh -e /etc/init.d/xvfb start'
  - 'RAILS_ENV=test bundle exec rake db:migrate'
script:
  - 'RAILS_ENV=test bundle exec rspec spec/'
